// This file is generated by FlutterFire CLI.
// Run: flutterfire configure
// to regenerate this file with your project's actual Firebase options.
//
// DO NOT commit real API keys to source control.
// Use environment variables or a secrets manager in CI/CD.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported by this app.');
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('Unknown platform: $defaultTargetPlatform');
    }
  }

  // ─── REPLACE ALL VALUES BELOW with your real Firebase project config ───
  // Run `flutterfire configure` to auto-generate this file.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn1qC0dGtqUt9G91ne4muBaCqlF4lGXUI',
    appId: '1:569679674083:web:d8af6249ea3a97fa5ae3d6',
    messagingSenderId: '569679674083',
    projectId: 'abdo-1689344702677',
    authDomain: 'abdo-1689344702677.firebaseapp.com',
    storageBucket: 'abdo-1689344702677.firebasestorage.app',
    measurementId: 'G-493BRCXHZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCEatOzRpGnuYXFK4ErAQDXMksFaCktkw',
    appId: '1:569679674083:android:ad48a13aba5815745ae3d6',
    messagingSenderId: '569679674083',
    projectId: 'abdo-1689344702677',
    storageBucket: 'abdo-1689344702677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCADO_03Jxy-Lk9k5SLJxwO6PgZH2CGhcQ',
    appId: '1:569679674083:ios:1b67b212d6ea9a1d5ae3d6',
    messagingSenderId: '569679674083',
    projectId: 'abdo-1689344702677',
    storageBucket: 'abdo-1689344702677.firebasestorage.app',
    androidClientId: '569679674083-hnen5h457tb1c09qga9ombh4vobspncv.apps.googleusercontent.com',
    iosClientId: '569679674083-celm39j3eph6e6prdalst747j899e11b.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCADO_03Jxy-Lk9k5SLJxwO6PgZH2CGhcQ',
    appId: '1:569679674083:ios:1b67b212d6ea9a1d5ae3d6',
    messagingSenderId: '569679674083',
    projectId: 'abdo-1689344702677',
    storageBucket: 'abdo-1689344702677.firebasestorage.app',
    androidClientId: '569679674083-hnen5h457tb1c09qga9ombh4vobspncv.apps.googleusercontent.com',
    iosClientId: '569679674083-celm39j3eph6e6prdalst747j899e11b.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn1qC0dGtqUt9G91ne4muBaCqlF4lGXUI',
    appId: '1:569679674083:web:ecb07f8accf4a6bf5ae3d6',
    messagingSenderId: '569679674083',
    projectId: 'abdo-1689344702677',
    authDomain: 'abdo-1689344702677.firebaseapp.com',
    storageBucket: 'abdo-1689344702677.firebasestorage.app',
    measurementId: 'G-PZDZ77VSHE',
  );

}